services:
  # Backend API Service
  - type: web
    name: chatbot-backend
    env: docker   # <-- switch from python to docker
    plan: free    # Change to 'starter' for $7/month always-on
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false

  # PostgreSQL Database (Free)
  - type: pserv
    name: chatbot-db
    plan: free

  # Static Frontend (Free)
  - type: static
    name: chatbot-frontend
    buildCommand: echo "No build needed"
    staticPublishPath: .
